CREATE SCHEMA IF NOT EXISTS coderdojo;
GRANT USAGE ON SCHEMA coderdojo TO service_role;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA coderdojo TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA coderdojo TO service_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA coderdojo
GRANT ALL PRIVILEGES ON TABLES TO service_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA coderdojo
GRANT USAGE, SELECT ON SEQUENCES TO service_role;