//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoderDojo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Badge
    {
        public Badge()
        {
            this.MemberBadges = new HashSet<MemberBadge>();
        }
    
        public System.Guid Id { get; set; }
        public string Achievement { get; set; }
        public Nullable<System.Guid> BadgeCategoryId { get; set; }
        public bool Deleted { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<MemberBadge> MemberBadges { get; set; }
        public virtual BadgeCategory BadgeCategory { get; set; }
    }
}
