//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoderDojo
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberAttendance
    {
        public System.Guid Id { get; set; }
        public System.Guid MemberId { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
