//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoderDojo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public Team()
        {
            this.Members = new HashSet<Member>();
        }
    
        public System.Guid Id { get; set; }
        public string TeamName { get; set; }
        public string HexCode { get; set; }
        public bool Deleted { get; set; }
        public string Goal { get; set; }
        public string Notes { get; set; }
    
        public virtual ICollection<Member> Members { get; set; }
    }
}
